[package]
name = "linux-kernel-module"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1"

[build-dependencies]
bindgen = "*"
cc = "1.0"
shlex = "0.1"
