[package]
name = "linux-kernel-module"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]

[dependencies]
bitflags = "1"

[build-dependencies]
bindgen = "0.42.3"
cc = "1.0"
shlex = "0.1"
